global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
- job_name: prometheus
  static_configs:
    - targets: [ "localhost:9090" ]
- job_name: 'product_service'
  metrics_path: '/actuator/prometheus'
  static_configs:
    - targets: ['product-service:8080']
      labels:
        application: 'Product Service App'
- job_name: 'order_service'
  metrics_path: '/actuator/prometheus'
  static_configs:
    - targets: [ 'order-service:8080' ]
      labels:
        application: 'Order Service App'
- job_name: 'inventory_service'
  metrics_path: '/actuator/prometheus'
  static_configs:
    - targets: ['inventory-service:8080']
      labels:
        application: 'Inventory Service App'
