apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-app
  template:
    metadata:
      labels:
        app: inventory-app
    spec:
      containers:
        - name: inventory-app-container
          image: mrwin95/inventory-service-dk:latest
          imagePullPolicy: Always
          args: ["--spring.profiles.active=k8s"]
          ports:
            - containerPort: 8084
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-svc
spec:
  type: ClusterIP
  selector:
    app: inventory-app
  ports:
    - port: 80
      protocol: "TCP"
      targetPort: 8084
