apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-app
  template:
    metadata:
      labels:
        app: order-app
    spec:
      containers:
        - name: order-app-container
          image: mrwin95/order-service-dk:latest
          imagePullPolicy: Always
          args: ["--spring.profiles.active=k8s"]
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: order-svc
spec:
  type: ClusterIP
  selector:
    app: order-app
  ports:
    - port: 80
      protocol: "TCP"
      targetPort: 8081
