apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-app
  template:
    metadata:
      labels:
        app: product-app
    spec:
      containers:
        - name: product-app-container
          image: mrwin95/product-service-dk:latest
          imagePullPolicy: Always
          args: ["--spring.profiles.active=k8s"]
          ports:
            - containerPort: 9091
---
apiVersion: v1
kind: Service
metadata:
  name: product-svc
spec:
  type: ClusterIP
  selector:
    app: product-app
  ports:
    - port: 80
      protocol: "TCP"
      targetPort: 9091
