apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipkin-app
  template:
    metadata:
      name: zipkin-app
      labels:
        app: zipkin-app
    spec:
      containers:
        - name: zipkin-app-container
          image: openzipkin/zipkin
          imagePullPolicy: Always
          ports:
            - containerPort: 9411

---
apiVersion: v1
kind: Service
metadata:
  name: zipkin-app-svc
  labels:
    app: zipkin-app-svc
spec:
  type: ClusterIP
  selector:
    app: zipkin-app
  ports:
    - port: 9411
      protocol: "TCP"
      targetPort: 9411
